/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package miniprojet;

import java.awt.GridLayout;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

public class FenetreDeJeu extends javax.swing.JFrame {

    private JButton[][] boutonsGrille;
    private int ligneActive = 0;
    private PlateauDeJeu plateau;
    private final String[] COULEURS_POSSIBLES = {"r", "b", "v", "j"};
    private final java.awt.Color[] COULEURS_REELLES = {
        java.awt.Color.RED,
        java.awt.Color.BLUE,
        java.awt.Color.GREEN,
        java.awt.Color.YELLOW
    };
    private JLabel[] resultLabels;

    public FenetreDeJeu() {
        initComponents();
        int nbLignes = 10;
        int nbColonnes = 4;
        plateau = new PlateauDeJeu(COULEURS_POSSIBLES);

        boutonsGrille = new JButton[nbLignes][nbColonnes];
        jPanel1.setLayout(new GridLayout(nbLignes, nbColonnes));

        resultLabels = new JLabel[nbLignes];
        jPanel3.setLayout(new GridLayout(nbLignes, 1));
        for (int i = 0; i < nbLignes; i++) {
            resultLabels[i] = new JLabel("Résultats ligne " + (i + 1) + ": -/-");
            jPanel3.add(resultLabels[i]);
        }

        for (int i = 0; i < nbLignes; i++) {
            for (int j = 0; j < nbColonnes; j++) {
                JButton bouton_cellule = new JButton();
                bouton_cellule.setText("");
                bouton_cellule.setEnabled(i == 0);
                bouton_cellule.setOpaque(true);
                bouton_cellule.setBorderPainted(false);

                final int currentRow = i;
                final int currentCol = j;

                bouton_cellule.addActionListener(new java.awt.event.ActionListener() {
                    private boolean isFirstClick = true;
                    private int currentLetterIndex = 0;

                    @Override
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        if (isFirstClick) {
                            bouton_cellule.setBackground(COULEURS_REELLES[0]);
                            bouton_cellule.setText("r");
                            bouton_cellule.setForeground(COULEURS_REELLES[0]);
                            isFirstClick = false;
                        } else {
                            currentLetterIndex = (currentLetterIndex + 1) % COULEURS_POSSIBLES.length;
                            bouton_cellule.setBackground(COULEURS_REELLES[currentLetterIndex]);
                            bouton_cellule.setText(COULEURS_POSSIBLES[currentLetterIndex]);
                            bouton_cellule.setForeground(COULEURS_REELLES[currentLetterIndex]);
                        }
                    }
                });

                boutonsGrille[i][j] = bouton_cellule;
                jPanel1.add(bouton_cellule);
            }
        }

        JOptionPane.showMessageDialog(this, 
            "La combinaison secrète est : " + plateau.getCombinaisonSecrete(), 
            "Combinaison Secrète", 
            JOptionPane.INFORMATION_MESSAGE);
    }
    // Le reste du code reste inchangé...


    // Le reste du code reste inchangé...


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(806, 802));

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        jPanel1.setPreferredSize(new java.awt.Dimension(600, 400));
        jPanel1.setSize(new java.awt.Dimension(600, 400));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 590, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 390, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel2.setPreferredSize(new java.awt.Dimension(600, 100));
        jPanel2.setSize(new java.awt.Dimension(600, 100));

        jLabel1.setFont(new java.awt.Font("Monaco", 0, 24)); // NOI18N
        jLabel1.setText("MASTERMIND");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(235, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(219, 219, 219))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel1)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(0, 153, 153));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 138, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );

        jPanel4.setBackground(new java.awt.Color(0, 153, 153));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 73, Short.MAX_VALUE)
        );

        jButton1.setText("Valider");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(0, 66, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(212, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        boolean ligneValidee = true;
    String[] couleursLigne = new String[4];  // Tableau pour stocker les couleurs de la ligne active

    // Récupération des couleurs de la ligne active
    for (int j = 0; j < boutonsGrille[ligneActive].length; j++) {
        String couleur = boutonsGrille[ligneActive][j].getText();
        if (couleur.isEmpty()) {
            ligneValidee = false;
            break;
        }
        couleursLigne[j] = couleur;  // Récupère les couleurs de la ligne
    }

    if (ligneValidee) {
        // Crée une nouvelle combinaison à partir des couleurs sélectionnées
        Combinaison tentative = new Combinaison();
        for (String couleur : couleursLigne) {
            tentative.ajouterPion(couleur);  // Ajoute chaque couleur à la tentative
        }

        // Utilisation de l'instance plateau pour vérifier la combinaison
        int exact = plateau.verifierCombinaisonExacte(tentative);
        int correctes = plateau.verifierCouleursCorrectes(tentative);

        // Affiche les résultats sur le JPanel3
        if (ligneActive < resultLabels.length) {
            resultLabels[ligneActive].setText("Exactes : " + exact + ", Correctes : " + correctes);
        } else {
            // Ajouter une vérification de taille avant d'ajouter des résultats
            System.out.println("Erreur : ligneActive dépasse la taille de resultLabels.");
        }

        // Désactive les boutons de la ligne actuelle
        for (int j = 0; j < boutonsGrille[ligneActive].length; j++) {
            boutonsGrille[ligneActive][j].setEnabled(false);
        }

        // Vérification de la victoire
        if (exact == 4) {
            JOptionPane.showMessageDialog(this, "Félicitations, vous avez trouvé la combinaison secrète !", 
                                          "Victoire", JOptionPane.INFORMATION_MESSAGE);
            jButton1.setEnabled(false); // Désactive le bouton Valider une fois le jeu terminé
            return; // Assurez-vous de sortir de la méthode après avoir affiché le message de victoire
        } else {
            // Activer la ligne suivante si elle existe
            ligneActive++;
            if (ligneActive < boutonsGrille.length) {
                for (int j = 0; j < boutonsGrille[ligneActive].length; j++) {
                    boutonsGrille[ligneActive][j].setEnabled(true);
                }
            } else {
                jButton1.setEnabled(false); // Désactive le bouton "Valider" si c'est la dernière ligne
                JOptionPane.showMessageDialog(this, "Vous avez épuisé toutes vos tentatives. Vous avez perdu.", 
                                              "Fin du jeu", JOptionPane.INFORMATION_MESSAGE);
            }
        }
    } else {
        JOptionPane.showMessageDialog(this, 
            "Veuillez remplir toutes les cellules de la ligne avant de valider.", 
            "Erreur", JOptionPane.ERROR_MESSAGE);
    }
     
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FenetreDeJeu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FenetreDeJeu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FenetreDeJeu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FenetreDeJeu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FenetreDeJeu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables
}

